### ISSUE TITLE
Hold does not work

### ISSUE THREAD

**Issue by ljstrnadiii** [monome-community/polygome#1]
Hey,

The hold button does not work. When I press it it launches other random notes I can not get to turn off. The Max window says that the matrix cells are out of bound as well. I am not sure if that is an error or not. 

I also took a look at BEAP and could not find polygome. Any idea where the "maintained" version is located in BEAP?

**Comment by tehn** [comment]
https://github.com/stretta/gridlab

**Comment by tehn** [comment]
https://github.com/stretta/gridlab
